version: '3'

services:
  database:
    image: bitnami/postgresql
    container_name: modular_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=modular_db