services:
  database:
    image: postgres
    container_name: modular-api
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: 'modular_db'
    ports:
      - '5432:5432'